apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: hamamooz-vmagent
  namespace: monitoring-system
spec:
  serviceScrapeNamespaceSelector:
    matchNames:
      - monitoring-system

  serviceScrapeSelector:
    matchLabels: {}

  replicaCount: 1

  scrapeInterval: 15s

  remoteWrite:
    - url: "http://hamamooz-vmsingle.monitoring-system.svc:8428/api/v1/write"
