apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: django-metrics
  namespace: monitoring-system
spec:
  namespaceSelector:
    matchNames:
      - application
  selector:
    matchLabels:
      service: django
  endpoints:
    - port: metrics
      path: /api/metrics
