apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: hamamooz-vmsingle
  namespace: monitoring-system
spec:
  retentionPeriod: "4d"
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
